<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ThreatFusion.Threat.API</AssemblyName>
    <RootNamespace>ThreatFusion.Threat.API</RootNamespace>
    <UserSecretsId>bf4a6118-3270-4922-a0d7-65ecebbe541d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThreatFusion.Threat.Application\ThreatFusion.Threat.Application.csproj" />
    <ProjectReference Include="..\ThreatFusion.Threat.Infrastructure\ThreatFusion.Threat.Infrastructure.csproj" />
  </ItemGroup>

</Project>
